### PR TITLE
fix pulls filter

### PR DESCRIPTION
**Pull request by heelc29**
#### Summary of Changes

image
fix pulls filters
use bind for database query

#### Testing Instructions

test if filters work (applied, rtc, npm, draft)

### CODE REVIEW

**Comment by roland-d** [comment]
Thank you @heelc29

**Comment by fgsw** [comment]
@roland-d do you plan a release including this fix? I wanted report the filter issue and see, its fixed allready.

**Comment by roland-d** [comment]
@fgsw You are commenting on a pull request that was merged into the core of the patch tester almost 1 year ago. There have been new releases since. If you believe there is still an issue, please file a new issue with the steps to reproduce it and I can check. No problem.

**Comment by heelc29** [comment]
@roland-d No, there hasn't been a new release for a year

**Comment by roland-d** [comment]
@heelc29 :scream: Oh my gosh the last release was 1 year to date. I will see if I can find some time this week to put out a new release with the fixes that were already merged.

Still annoying that Github does not notify me of posts in this repo unless I am mentioned.

**Pull request merged**
