### PR TITLE
Remove mootools

### PR DESCRIPTION
**Pull request by dgt41**
Mootools is not needed here, so lets drop it!
Also the inline script is better to go through API

### CODE REVIEW

**Comment by mbabker** [comment]
This doesn't kill the modal for the fetch process, does it?

**Comment by dgt41** [comment]
No the fetch is jquery

**Comment by dgt41** [comment]
@mbabker the modal is bootstrap https://github.com/joomla-extensions/patchtester/blob/master/administrator/components/com_patchtester/PatchTester/View/Pulls/PullsHtmlView.php#L106-L117

**Comment by mbabker** [comment]
Ya that's what I couldn't remember off hand, if a Bootstrap modal was being used or if it was the older Squeezebox one.

**Pull request merged**
