### PR TITLE
php 81. deprecated

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #341 .

#### Testing Instructions
see #341

### CODE REVIEW

**Comment by toivo** [comment]
The <html>
<body>
<h1 id="patchtester-progress-header" style="box-sizing: border-box; color: var(--template-bg-dark); font-weight: 400; line-height: 1.2; margin-bottom: 0.5rem; margin-top: 0px; font-size: calc(1.29rem + 0.48vw); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An error has occurred while fetching the data from GitHub.</h1><p id="patchtester-progress-message" style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"><font size="1" style="box-sizing: border-box;">

( ! ) Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in C:\www\joomla4test\libraries\src\MVC\Model\ListModel.php on line 586
--


1 | 0.0002 | 365680 | {main}( ) | ...\index.php:0
2 | 0.0002 | 366448 | require_once( 'C:\www\joomla4test\administrator\includes\app.php ) | ...\index.php:32
3 | 0.0088 | 1080360 | Joomla\CMS\Application\CMSApplication->execute( ) | ...\app.php:63
4 | 0.0094 | 1169064 | Joomla\CMS\Application\AdministratorApplication->doExecute( ) | ...\CMSApplication.php:278
5 | 0.0672 | 2393008 | Joomla\CMS\Application\AdministratorApplication->dispatch( $component = ??? ) | ...\AdministratorApplication.php:186
6 | 0.0687 | 2363696 | Joomla\CMS\Component\ComponentHelper::renderComponent( $option = 'com_patchtester', $params = ??? ) | ...\AdministratorApplication.php:143
7 | 0.0706 | 2387616 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch( ) | ...\ComponentHelper.php:389
8 | 0.0712 | 2404512 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure:C:\www\joomla4test\libraries\src\Dispatcher\LegacyComponentDispatcher.php:68-70}( $path = 'C:\\www\\joomla4test\\administrator/components/com_patchtester/patchtester.php' ) | ...\LegacyComponentDispatcher.php:71
9 | 0.0712 | 2404960 | require_once( 'C:\www\joomla4test\administrator\components\com_patchtester\patchtester.php ) | ...\LegacyComponentDispatcher.php:69
10 | 0.0715 | 2405600 | PatchTester\Controller\FetchController->execute( ) | ...\patchtester.php:44
11 | 0.0724 | 2428144 | PatchTester\Model\PullsModel->requestFromGithub( $page = 1 ) | ...\FetchController.php:56
12 | 0.2578 | 2408936 | Joomla\CMS\MVC\Model\BaseModel->getState( $property = ???, $default = ??? ) | ...\PullsModel.php:366
13 | 0.2578 | 2408936 | Joomla\CMS\MVC\Model\ListModel->populateState( $ordering = ???, $direction = ??? ) | ...\StateBehaviorTrait.php:58
14 | 0.2578 | 2408936 | strtoupper( $string = NULL ) | ...\ListModel.php:586

</font>{"success":true,"message":"Processing page 2 of 3 pages of GitHub data","messages":null,"data":{"complete":false,"page":2,"lastPage":3}}</p>
</body>
</html>An error has occurred while fetching the data from GitHub.

( ! ) Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in C:\www\joomla4test\libraries\src\MVC\Model\ListModel.php on line 586
Call Stack
#	Time	Memory	Function	Location
1	0.0002	365680	{main}( )	...\index.php:0
2	0.0002	366448	require_once( 'C:\www\joomla4test\administrator\includes\app.php )	...\index.php:32
3	0.0088	1080360	Joomla\CMS\Application\CMSApplication->execute( )	...\app.php:63
4	0.0094	1169064	Joomla\CMS\Application\AdministratorApplication->doExecute( )	...\CMSApplication.php:278
5	0.0672	2393008	Joomla\CMS\Application\AdministratorApplication->dispatch( $component = ??? )	...\AdministratorApplication.php:186
6	0.0687	2363696	Joomla\CMS\Component\ComponentHelper::renderComponent( $option = 'com_patchtester', $params = ??? )	...\AdministratorApplication.php:143
7	0.0706	2387616	Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch( )	...\ComponentHelper.php:389
8	0.0712	2404512	Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure:C:\www\joomla4test\libraries\src\Dispatcher\LegacyComponentDispatcher.php:68-70}( $path = 'C:\\www\\joomla4test\\administrator/components/com_patchtester/patchtester.php' )	...\LegacyComponentDispatcher.php:71
9	0.0712	2404960	require_once( 'C:\www\joomla4test\administrator\components\com_patchtester\patchtester.php )	...\LegacyComponentDispatcher.php:69
10	0.0715	2405600	PatchTester\Controller\FetchController->execute( )	...\patchtester.php:44
11	0.0724	2428144	PatchTester\Model\PullsModel->requestFromGithub( $page = 1 )	...\FetchController.php:56
12	0.2578	2408936	Joomla\CMS\MVC\Model\BaseModel->getState( $property = ???, $default = ??? )	...\PullsModel.php:366
13	0.2578	2408936	Joomla\CMS\MVC\Model\ListModel->populateState( $ordering = ???, $direction = ??? )	...\StateBehaviorTrait.php:58
14	0.2578	2408936	[strtoupper](http://www.php.net/function.strtoupper)( $string = NULL )	...\ListModel.php:586
{"success":true,"message":"Processing page 2 of 3 pages of GitHub data","messages":null,"data":{"complete":false,"page":2,"lastPage":3}}call stack displayed inside the Fetch Data modal is different:

**Comment by N6REJ** [comment]
The error listed with this pr no longer exists in patch_tester
```
An error has occurred while fetching the data from GitHub.

Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\src\MVC\Model\ListModel.php on line 543

Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 24

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in E:\Bearsampp\www\j4\libraries\src\HTML\Helpers\StringHelper.php on line 132
{"success":true,"message":"Processing page 2 of 3 pages of GitHub data","messages":null,"data":{"complete":false,"page":2,"lastPage":3}}
```

**Comment by roland-d** [comment]
@alikon There is a merge conflict due to the PSR-12 conversion, however I have also wrote in the issue that I cannot reproduce the issue on Joomla 4.2.3. Do you still get them?

**Comment by alikon** [comment]
no more

**Pull request closed without merging**
