### PR TITLE
makes icons conform to pr #28075 in J! 4.0-dev

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

#### Summary of Changes
changes icon names to be fa compliant
#### Testing Instructions
see https://github.com/joomla/joomla-cms/pull/28075

### CODE REVIEW

**Comment by richard67** [comment]
Works when https://github.com/joomla/joomla-cms/pull/28075 is applied to the CMS.

So this here should not be merged before https://github.com/joomla/joomla-cms/pull/28075 into the 4.0-dev branch of the CMS.

**Comment by richard67** [comment]
@N6REJ This PR works, but the icon of the "Reset" button is also shown without this PR. The reason might be some magic icon to fa class mapping done in the toolbar helper for that icon. Wouldn't it be more consistent to add such mapping also for the "Fetch Data" button (`icon-refresh` to `fas fa-sync`)? If so, please make a PR for the CMS. We could use the patchtester for testing it as long as this PR here is not merged.

Without PR:
j4-patchtester-icons-before

j4-patchtester-icons-before_2

With PR:
j4-patchtester-icons-after

**Comment by N6REJ** [comment]
@richard67 I looked over this today but I'm having a hard time thinking today.. There seems to be more going on then I'm seeing today.  I'll get back to this in the next day to 2.

**Comment by N6REJ** [comment]
@richard67 ok, so the bigger problem is the non-use of toolbar grid like J! 4.0 uses it.
image
you'll notice the "icon" in both.  This is due to toolbar grid not using the changes in 4.0 that were merged recently.  W/o this being fixed the rest can't be fixed properly.

**Comment by N6REJ** [comment]
> @N6REJ This PR works, but the icon of the "Reset" button is also shown without this PR. The reason might be some magic icon to fa class mapping done in the toolbar helper for that icon. Wouldn't it be more consistent to add such mapping also for the "Fetch Data" button (`icon-refresh` to `fas fa-sync`)? If so, please make a PR for the CMS. We could use the patchtester for testing it as long as this PR here is not merged.

You lost me here.... Not sure what needs a pr.

**Comment by richard67** [comment]
Yes.

**Comment by N6REJ** [comment]
how in the world is icon- still being the default class?

**Comment by richard67** [comment]
Don't know for sure. But at least it should still work for 3rd party stuff.

**Comment by N6REJ** [comment]
cept it's mucking with the mapping.. there is no such thing as icon-sync

**Comment by N6REJ** [comment]
I wish I understand how he's creating the grid.. doesn't seem like it's the right way

**Comment by richard67** [comment]
> cept it's mucking with the mapping.. there is no such thing as icon-sync

@N6REJ But there is `icon-refresh` to be mapped to `fas fa-sync`, see my comment above.

**Comment by richard67** [comment]
@roland-d This one here can be merged now. I've just tested and it works, the icon of the "Fetch Data" button is fixed.

**Pull request merged**
