### PR TITLE
Remove language code prefix like "en-GB." from language files' names for Joomla 4 and other language file fixes

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issues #265 and #263 .

#### Summary of Changes

- Remove language code prefix, e.g. "en-GB." from name of language files like it was done for the CMS in the 4.0-dev branch.
- Copy the `COM_PATCHTESTER_XML_DESCRIPTION` string from `.sys.ini` to `.ini`.
- Alpha order the new sting `COM_PATCHTESTER_PATCH_BREAKS_SITE` to the right place in the en-GB file.
- Copy the same new sting to the en-US file.
- Translate the same new string to German and add it to the de-DE file.

#### Testing Instructions

Install following patch tester 4 rc-1 package patched with the modifications of this Pull Request (PR): [https://test5.richard-fath.de/com_patchtester_4.0.0.rc2_pr-268.zip](https://test5.richard-fath.de/com_patchtester_4.0.0.rc2_pr-268.zip) on a Joomla 4 nightly build or current 4.0-dev branch.

Check that patchtester works without any language string problems which were not there without this PR.

### CODE REVIEW

**Comment by richard67** [comment]
@roland-d Please ask the translators to check if my changes in `crowdin.yaml` are ok.

**Comment by richard67** [comment]
@bakual Could you have a look if the changes for crowdin.yaml in this PR here are correct?

**Comment by Bakual** [comment]
As I'm not involved with the Patchtester project on Crowdin I don't really know. You will have to check with the sync tool that is set up - I think it doesn't use the Crowdin GitHub integration but some other script.

**Comment by richard67** [comment]
@roland-d At this point I am out, I don't know anything about any sync tool.

**Pull request merged**
