### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by alikon**
#### Summary of Changes
added language it-IT

#### Testing Instructions
use patchtester with it-IT language

### CODE REVIEW

**Comment by mbabker** [comment]
Thanks!

For reference, we just got set up on [Crowdin](https://crowdin.com/project/joomla-patchtester) today.  I've gone ahead and uploaded these translations there, for the future just make updates there and I'll regularly sync things up.

**Comment by MATsxm** [comment]
@alikon 
could you please check here: https://crowdin.com/project/joomla-patchtester/it#
and add the missing string on it? 
Thanks

**Comment by alikon** [comment]
@mbabker thx ,i didn't know...
@MATsxm what strings are missed?

**Comment by MATsxm** [comment]
@alikon 
Sorry, no prob... our other it-IT specialist did them already :wink: 
Thanks for the help!

**Comment by alikon** [comment]
do we have a synch issue ?

**Comment by mbabker** [comment]
When you upload through the API strings that match the source are considered untranslated, so I went through on all those strings and applied the English text to mark them as translated (since that's how they were in the files here).

**Pull request merged**
