### PR TITLE
314 missing pulls

### PR DESCRIPTION
**Pull request by weeblr**
Pull Request for Issue #314 .

#### Summary of Changes

Use pulls rest API endpoint instead of issues endpoint to fetch the list of PRs. Using issues endpoint caused only a subset of PRs to be retrieved.

#### Testing Instructions

Applying change make last 100 PR (batchsize) to be listed in the patch tester admin.

### CODE REVIEW

**Comment by weeblr** [comment]
@roland-d Can you make sure to pull that one in as well? Joomla 3 version has the same problem as the J4 version. Thanks

**Comment by richard67** [comment]
@weeblr Maybe you can fix code style before? You have removed an `if` condition around a code block, so that code block needs one level = one tab less indentation:
https://github.com/joomla-extensions/patchtester/pull/315/files#diff-52387c1e54fadcf3939c94d09d0c914e6eaffd024fe8fd3f47ac4bc289ab01e1R373-R399

**Comment by weeblr** [comment]
@richard67 I have attempted to reformat, I'm doing it in Github directly, not the easiest there.

**Comment by richard67** [comment]
@weeblr Looks ok here locally with an editor which shows tabs and spaces (if I want that). Not easy in the GitHub UI, I agree. Thanks so far.

I don't know if and when @roland-d 's plans a 3.0.0 release.

**Comment by weeblr** [comment]
Well I hope he does cause that's where the problem lies for me and at least on issue solved but pending tests. I have testers, they spent times trying to start using patchtester only to find it would not show the PR I was asking them to test.

Wonder how this has affected the development and testing of Joomla 4 indeed, this has likely been going on for a while now. If people did not see PR in the patchtester, then obviously they could not test them!

**Pull request merged**
