### PR TITLE
Add 3.0.0 beta to the update server with beta update tag

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

Add 3.0.0 beta to the update server with beta update tag

#### Testing Instructions

Merge this set the update stability in the backend to beta you see the update.
Switch back to stable (default) no update should be shown.

### CODE REVIEW

**Comment by mbabker** [comment]
3.0 is Joomla 3.7+ only.  Also, if this is going to be included (which I don't see a reason it shouldn't), https://github.com/joomla-extensions/patchtester/blob/master/build/patchtester/release.php will need to be updated so it is able to update the manifest file versions in the right sections.

**Comment by zero-24** [comment]
i have just done the 3.7+ only thing. I'm not sure what do you want from me with the release script.

Don't we just need to add / update the version tag here: https://github.com/joomla-extensions/patchtester/blob/master/build/patchtester/release.php#L116 ?

btw the mainfest file changes are not save in the current implementation as you update now both update sections ;)

**Comment by mbabker** [comment]
So the problem with that release script as it is now is when it is run it would update the URL for both the stable and beta channels.  So we need to sort out a way to be able to only update the stable or beta areas, can work on that more later.  It'll get even worse if/when we add Joomla 4.0 to the list.

Either way this is good enough for now, I just have to remember to manually check that one 😉

**Comment by zero-24** [comment]
What about disabeling this until it is working ;)

**Comment by zero-24** [comment]
Thanks for merging.

**Pull request merged**
