### PR TITLE
Adds Update server

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Adds update server to patchtester.

#### Testing Instructions

Check code difference.

### CODE REVIEW

**Comment by mbabker** [comment]
I'm gonna sit on this until I tag something as stable.  Simply because I've gone in and made changes to the database schema file between beta releases which doesn't make upgrades practical this way.

I guess one day I should mark "stable" blockers and not just arbitrarily keep calling this beta.

**Comment by andrepereiradasilva** [comment]
> I guess one day I should mark "stable" blockers and not just arbitrarily keep calling this beta.

IMHO the patchtester is ready for 2.0.0 stable :)
I've been using it for months and works great!

**Comment by photodude** [comment]
I think at the very least the patch tester is a little overdue for a beta 5
and I hear there is a Joomla magazine article coming that is highlighting "testing" and uses the Patch tester. Might be a reason to consider a path to stable.

**Comment by mbabker** [comment]
Let me think this through.  I know #124 needs to be dealt with somehow, the fetcher modal could really use some UI love (but I still don't know how else to deal with it, it's not like we have static access to all the data AFAIK), and if we decide to do something with #88 I'd rather do it sooner than later.  A new beta package is feasible though.

**Pull request merged**
