### PR TITLE
Resolve issue when searching by pull id "id:xxxxx"

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
To test search for "id:xxxxx" where xxxxx is the pull request id.

### CODE REVIEW

**Comment by sovainfo** [comment]
To test:
Enter xxxx in search field and press search button, where xxxx is the PR. Either xxxx or id:xxxx. Expect the PR to be found. Use a high number like 9095. Currently found by id:9 and not by 9095.
Note that id (9) is depending on the fetch of the pulls from git, probably different in your environment.

**Comment by andrepereiradasilva** [comment]
id:9107 search works.

i have beta 4, not latest staging, in beta 4 the changes works, i see now you can search just for xxxxx.
I will check.

**Comment by sovainfo** [comment]
Used Patch Tester 2.0.0.beta4 where id:9095 didn't work!

So, I agree with your patch. It should use pull_id and NOT id in the where clause.
Tried to use patchtester to patch patchtester but failed. Manually using pull_id instead of id works.

**Comment by andrepereiradasilva** [comment]
Can you test now (latest staging + this PR).

**Comment by sovainfo** [comment]
Tested OK

Installed the b4, downloaded zip and overwrote com_patchtester. Applied PR manually.
Filtered on 9095, 909 and id:9095. All results were as expected.

Is it possible to use patchtester on patchtester?

**Comment by andrepereiradasilva** [comment]
i think so

image

**Comment by mbabker** [comment]
If a repo is structured with Joomla's file structure, the patch tester can be used against it.  Ironically, that means patch tester can test the patch tester, but not the weblinks component.

**Comment by sovainfo** [comment]
That is what I thought, but receiving : Error retrieving pull requests from GitHub: Not Found

**Comment by mbabker** [comment]
Don't have the time at the moment to dig into that and not found is too generic of a message (not finding a repo, an issue...).

**Comment by andrepereiradasilva** [comment]
there are no PR in this repository at the moment ...

**Comment by sovainfo** [comment]
Edited my previous comment. Everything is ok now when using joomla-extensions and patchtester.

Sorry for wasting your time.

**Comment by mbabker** [comment]
Ahh, ya, that one condition you'd never think to check because 99.9% of people are using this on the CMS repo which will never have a 0 pull request state :laughing:

**Comment by andrepereiradasilva** [comment]
ok so it's like this

image

@mbabker the problem was that i posted a wrong config. no problem in the patchtester

**Comment by sovainfo** [comment]
Indeed, that works. And yes, was surprised at first with an empty list, but figured it out myself. Then read the comments after mine.

Thanks for fixing and applying.

**Pull request merged**
